# Generated by Django 4.2.3 on 2023-08-05 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, verbose_name=100)),
                ('avatar', models.CharField(default=None)),
                ('description', models.CharField(default=None, verbose_name=100)),
                ('is_private', models.BooleanField(default=False)),
            ],
        ),
    ]
