# Generated by Django 4.2.3 on 2023-08-19 01:19

from django.db import migrations, models
import django_minio_backend.models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_alter_group_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='avatar',
            field=models.ImageField(blank=True, storage=django_minio_backend.models.MinioBackend(bucket_name='media', upload_to=django_minio_backend.models.iso_date_prefix), upload_to=''),
        ),
    ]
