# Generated by Django 4.2.3 on 2023-08-19 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0006_alter_group_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='avatar',
            field=models.ImageField(blank=True, storage='storages.backends.s3boto3.S3Boto3Storage', upload_to=''),
        ),
    ]
