# Generated by Django 4.2.3 on 2023-08-06 12:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('platforms', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='image',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='platform',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='platform2users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='platform_link',
            name='link',
            field=models.CharField(blank=True),
        ),
    ]
