# Generated by Django 4.2.3 on 2023-09-17 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activityApp', '0003_alter_groupposts_id_alter_userposts_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grouppostcomment',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='groupposts',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='userpostcomment',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='userposts',
            options={'ordering': ['-date']},
        ),
    ]
