# Generated by Django 4.2.3 on 2023-09-23 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activityApp', '0005_alter_grouppostcomment_id_alter_userpostcomment_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grouppostcomment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='userpostcomment',
            options={},
        ),
    ]
