# Generated by Django 4.2.3 on 2023-08-06 12:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_bio_user_id_alter_user_friends_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio',
            name='birthday',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='bio',
            name='sex',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AlterField(
            model_name='bio',
            name='user_description',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar_id',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='galary',
            field=models.ManyToManyField(blank=True, related_name='images2users', to='profiles.userimages'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=14),
        ),
        migrations.AlterField(
            model_name='user',
            name='surname',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='user_friends',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='friends2users', to=settings.AUTH_USER_MODEL),
        ),
    ]
