# Generated by Django 4.2.3 on 2023-08-06 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_bio_birthday_alter_bio_sex_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar_id',
            field=models.IntegerField(default=1),
        ),
    ]
