# Generated by Django 4.2.3 on 2023-09-10 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_user_avatar_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cover_id',
            field=models.IntegerField(default=0),
        ),
    ]
