# Generated by Django 4.2.3 on 2023-09-10 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_bio_birthday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cover_id',
        ),
        migrations.AddField(
            model_name='user',
            name='cover',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='userimages',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
